### PR TITLE
Window resizing and new run level

### LINKED ISSUE #118: Major bug in wgpu / egui integration
Manipulations with application window and egui window widgets may trigger `ScissorRect` changes and WGPU crashes on some values:

```
Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 4662, Vulkan)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

```

**Solution:**

1. Upgrade WGPU and EGUI dependencies to the most recent versions
2. Verify, what triggers the issue on WGPU side and how  `ScissorRect` can be validated
3. May also happen, that window changes will require to be deffered

### PR DESCRIPTION
**Pull request by Lowentwickler**
This PR will:

- Add default traits implementation to data strutures
- Switch to use renderer's surface size instead of window's size for scissors rectangle calculation
- Switch from direct window resize to resize request
- Update winit dependency
- Add `RunLevel::PreRender` to ECS and Scheduler

Closes #118

### CODE REVIEW

File: dotrix_egui/src/lib.rs [hunk 1]
```diff
@@ -65,11 +69,20 @@ impl Egui {
...
+        renderer: &Renderer,
+        window: &Window,
+    ) {
         let scale_factor = self.scale_factor * window.scale_factor();
-        let surface_size = window.inner_size();
-        let surface_width = surface_size.x as f32;
-        let surface_height = surface_size.y as f32;
+
+        self.surface_scale_factor = scale_factor;
+        self.surface_size = renderer.surface_size();
```
Comment (Lowentwickler) [inline dotrix_egui/src/lib.rs:82]: Use surface size instead of window size.

**Review by ZKpot — APPROVED** [review]
